declare module 'lucide-react' {
  import { type FC, type SVGProps } from 'react'
  export type LucideIcon = FC<SVGProps<SVGSVGElement> & { size?: number; strokeWidth?: number }>
  export const Search: LucideIcon
  export const Plus: LucideIcon
  export const Bell: LucideIcon
  export const Sun: LucideIcon
  export const Moon: LucideIcon
  export const X: LucideIcon
  export const LogOut: LucideIcon
  export const CheckCircle: LucideIcon
  export const AlertCircle: LucideIcon
  export const Info: LucideIcon
  export const AlertTriangle: LucideIcon
  export const RefreshCw: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronRight: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ArrowLeft: LucideIcon
  export const Edit3: LucideIcon
  export const Trash2: LucideIcon
  export const Loader2: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const PawPrint: LucideIcon
  export const Heart: LucideIcon
  export const Activity: LucideIcon
  export const UtensilsCrossed: LucideIcon
  export const Calendar: LucideIcon
  export const Settings: LucideIcon
  export const Mail: LucideIcon
  export const Lock: LucideIcon
  export const Eye: LucideIcon
  export const EyeOff: LucideIcon
  export const Syringe: LucideIcon
  export const Stethoscope: LucideIcon
  export const Pill: LucideIcon
  export const Footprints: LucideIcon
  export const Timer: LucideIcon
  export const Flame: LucideIcon
  export const TrendingUp: LucideIcon
  export const TrendingDown: LucideIcon
  export const Dog: LucideIcon
  export const Utensils: LucideIcon
  export const Clock: LucideIcon
  export const RotateCcw: LucideIcon
  export const Scissors: LucideIcon
  export const Shield: LucideIcon
  export const Palette: LucideIcon
  export const Users: LucideIcon
  export const UserPlus: LucideIcon
  export const CalendarDays: LucideIcon
  export const Check: LucideIcon
  export const Camera: LucideIcon
  export const Play: LucideIcon
  export const Pause: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const MoreVertical: LucideIcon
  export const Trash: LucideIcon
  export const Download: LucideIcon
  export const Upload: LucideIcon
  export const Share2: LucideIcon
  export const Home: LucideIcon
  export const Menu: LucideIcon
  export const User: LucideIcon
  export const SearchX: LucideIcon
  export const Filter: LucideIcon
  export const SlidersHorizontal: LucideIcon
  export const Star: LucideIcon
  export const MessageCircle: LucideIcon
  export const Phone: LucideIcon
  export const MapPin: LucideIcon
  export const ExternalLink: LucideIcon
  export const Globe: LucideIcon
  export const HelpCircle: LucideIcon
  export const Image: LucideIcon
  export const Video: LucideIcon
  export const Music: LucideIcon
  export const FileText: LucideIcon
  export const BookOpen: LucideIcon
  export const Award: LucideIcon
  export const Gift: LucideIcon
  export const ThumbsUp: LucideIcon
  export const Send: LucideIcon
  export const Lightbulb: LucideIcon
  export const BarChart3: LucideIcon
}
